title: base-jekyll
email: 
description: 
baseurl: "/"
url: ""
author: 
type: 
lang: 
favicon: favicon.png
cover_og: cover-og.png

markdown: kramdown

collections:

sass:
    style: compressed
    sass_dir: _sass

permalink: /:title/

defaults:
  # -
  #   scope:
  #     type: projects
  #   values:
  #     layout: projects
  -
    scope:
      path: ""
    values:
      layout: "default"
